/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import conexao.ConexaoBD;
import infoMaquina.CadastrarMaquina;
import infoMaquina.CadastrarMaquinaLinux;
import infoMaquina.Cpu;
import infoMaquina.Disco;
import infoMaquina.Leituras;
import infoMaquina.Memoria;
import infoMaquina.SetupMaquina;
import infoMaquina.SistemaOperacional;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import oshi.util.FormatUtil;

/**
 *
 * @author admin
 */
public class TelaBemVindo extends javax.swing.JFrame {

    private final String userAtual;
    private final Integer func;

    /**
     * Creates new form TelaBemVindo
     */
    public TelaBemVindo(String userAtual, Integer func) throws IOException, SQLException {
        initComponents();
        conexao.ConexaoBD con = new ConexaoBD();
        SetupMaquina setup = new SetupMaquina();
        Leituras lt = new Leituras();

        this.userAtual = userAtual;
        this.func = func;

        CadastrarMaquina userWindows = null;
        CadastrarMaquinaLinux userLinux = null;
        SistemaOperacional sistema = new SistemaOperacional();
        if (sistema.getSistemaOperacional().contains("Microsoft Windows")) {
            userWindows = new CadastrarMaquina(func);
        } else {
            userLinux = new CadastrarMaquinaLinux(func);
        }

        if (!this.userAtual.equals("")) {
            String verificacaoMaquinaFuncionario = String.format("SELECT COUNT(*) AS 'Número Total' FROM [dbo].[Funcionario], [dbo].[Maquina] where Funcionario_idFuncionario = %s AND Funcionario_idFuncionario = idFuncionario", func);
            ResultSet resultadoQuery = con.getStmt().executeQuery(verificacaoMaquinaFuncionario);

            Boolean insert = false;

            while (resultadoQuery.next()) {
                if (resultadoQuery.getInt("Número Total") == 0) {
                    insert = true;
                }
            }
            if (insert) {
                if (userLinux != null) {
                    userLinux.CadastrarNovaMaquina();
                } else {
                    userWindows.CadastrarNovaMaquina();
                }
                ResultSet setupIdMaquina = con.getStmt().executeQuery(String.format("SELECT idMaquina FROM [dbo].[Maquina] WHERE Funcionario_IdFuncionario = %d", func));
                while (setupIdMaquina.next()) {
                    setup.idMaquina(setupIdMaquina.getInt("idMaquina"));
                }
                setup.statusComponentes();
                setup.componenteIdComponentes("CPU");
                setup.insertSetupMaquina();
                setup.componenteIdComponentes("DISCO");
                setup.insertSetupMaquina();
                setup.componenteIdComponentes("RAM");
                setup.insertSetupMaquina();
                setup.idSetupMaquina();
            }
        }

        lt.idSetupMaquina(func);
        new Timer().scheduleAtFixedRate(new TimerTask() {
            @Override
            public void run() {
                Cpu cpu = new Cpu();
                Memoria mem = new Memoria();
                Disco disc = new Disco();
                
                try {
                    lt.insertLeitura("CPU", cpu.usoCpu());
                    lt.insertLeitura("DISCO", Double.valueOf(disc.getDiskPercent(0)));
                    lt.insertLeitura("MEMORIA", mem.usoMemoria());

                } catch (SQLException | IOException ex) {
                    Logger.getLogger(TelaBemVindo.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }, 0, 3000);
    }

    private TelaBemVindo() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(63, 120, 158));
        jLabel2.setText("Bem vindo!");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Aplicação inicializada com sucesso!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel3)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel2)
                .addGap(35, 35, 35)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaBemVindo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaBemVindo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaBemVindo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaBemVindo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaBemVindo().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
